### ISSUE TITLE
Task 1 : Provide a dataset containing Ingredients and Departments

### ISSUE THREAD

**Issue by philippeTUESIGELEC** [GroceriStar/tensor-something#3]
**Assignee :** Philippe Tu
**Date of creation :** 31/03/2018
**Deadline :** None

**Task :** Provide a dataset containing foods, departments and nutrient 

**Status :** Done (08 / 04 / 2018)
End task comment : Results are in a csv file. Containing departments, ingredients and nutrient values. Units of nutrients are in column names. 
Result file : UGLResults.csv (master branch)

**Comment by atherdon** [comment]
- [ ] From where you'll get that data? 
- [ ] Will you pick recipes or grocery lists?
- [ ] Should I prepare some content for you?

**Comment by philippeTUESIGELEC** [comment]
**- From where you'll get that data? :** https://data.world/datafiniti/food-ingredient-lists , It is a 10k rows dataset containing recipes, types of ingredients (department) in it, and their ingredients. I'am currently working on separating ingredients and put a "department" on each of them.
- Second Dataset I'll be working on and merge with the first one : https://www.ars.usda.gov/ARSUserFiles/80400525/Data/SR27/asc/FOOD_DES.txt , It's an Opendata text file that contains ingredients, departments. Exactly 8618 rows in it. 
So that's around 19k rows of data I'am cleaning and preparing now,

**-Will you pick recipes or grocery lists? :** List of recipes (1st dataset), List of ingredients and their departments (2d dataset). For now, I don't plan to take other datasets as the two mentionned before are good data for your current need, the result will be satisfying.

**-Should I prepare some content for you :** Not really.

**Comment by atherdon** [comment]
amazing! i don't know about this open datasets. i was thinking about kaggle or https://world.openfoodfacts.org/ but there is no simple way to get what exactly i need for this moment. but for latest versions nutritional info will be a cool advantage for us...(from openfoodfacts)

**Comment by philippeTUESIGELEC** [comment]
Yes openfoodfact is an amazing source of data. We can use their data, the only thing we have to do in terms of rights is to say that the data comes from their website.

Openfoodfact data once downloaded is a mess to clean and prepare. I'll try to get into it when I've finished the first task. I'll create a issue ticket myself about this final objective of getting a dataset with nutritional facts once I've finished the first task.

**Comment by atherdon** [comment]
i was thinking about adding barcode scan into the app(right now there no app in process) and maybe using OFF will be a good source of data. 

it's not a problem for me to give a credit. so yeah, we'll list from were we grab the data.

**Comment by philippeTUESIGELEC** [comment]
I've updated the initial task ticket. I've discovered great data from Canada. 
It kinda contains every product you can find in supermarkets and all kind of shops where you want to by everything related to food, it's the best data I found of all my research of data.
Its made of a few csv files with 100+ different nutrient with values and their unit on each product (5690 products exactly). I think it suits your final need for Groceristar.
I'll keep you advised soon about it.

**Comment by atherdon** [comment]
this is really amazing news!
i cannot wait to add it to GS

**Comment by philippeTUESIGELEC** [comment]
Hi !
I've finished the job. I'll push it into the repository. Tell me what you think of it. All should be good here, I think i've made no mistakes while working on it.
Kind regards,
Philippe Tu.

**Comment by atherdon** [comment]
@philippeTUESIGELEC start to reviewing

**Comment by atherdon** [comment]
so we should plan to add nutrition schema into groceristar. there a lot of important data.
It's awesome. huuuge. really make my day(also get updates related to design + frontend pages today).

**Comment by atherdon** [comment]
what will be our next steps?

**Comment by atherdon** [comment]
our latest structure(not finished and this is good :)) about nutrition: https://github.com/ChickenKyiv/recipe-search-api/blob/master/bin/nutritions.js

**Comment by philippeTUESIGELEC** [comment]
Hi Arthur,

Happy to see that it corresponds to Groceristar needs. So I see that you're
planning to include the nutrition schema, that's great :) .
I'am studying Data so, are you interested in having something close to
machine learning to improve Groceristar ?

Regards,
Philippe Tu.

**Comment by atherdon** [comment]
For sure! i want to extend GS value and provide more value to my future
users.

my friend advice me - "find a Recommender system by Andrew Ng on youtube.
Go check it out. It is not a simple system and will be hard to come up on
your own."
what do you think about it?

**Comment by philippeTUESIGELEC** [comment]
Hi !
I'll open a new ticket myself about this recommendation system. I'am coming back to you soon (don't know when but soon) as I'll have many questions about it.
Can we close this Github issue ? Thanks ! 

Philippe.

**Comment by atherdon** [comment]
take your time! and thanks
